version: '3.8'

services:
  php:
    image: ghcr.io/blumilksoftware/php:8.0.3.1
    container_name: quiz-php
    working_dir: /application
    volumes:
      - .:/application
    networks:
      - quiz
    restart: unless-stopped

networks:
  quiz:
    driver: bridge
