version: '3.8'

services:
  web:
    image: nginx:1.19-alpine
    container_name: quiz-web
    working_dir: /application
    volumes:
      - ./environment/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/application
    networks:
      - quiz
    ports:
      - 80:80
    restart: unless-stopped

  php:
    build:
      context: environment/php
      dockerfile: Dockerfile
      args:
        XDEBUG_HOST: ${XDEBUG_HOST}
        XDEBUG_PORT: ${XDEBUG_PORT}
        XDEBUG_INSTALL: ${XDEBUG_INSTALL}
        XDEBUG_START_WITH_REQUEST: ${XDEBUG_START_WITH_REQUEST}
        XDEBUG_MODE: ${XDEBUG_MODE}
        XDEBUG_LOG_LEVEL: ${XDEBUG_LOG_LEVEL}
    container_name: quiz-php
    working_dir: /application
    user: ${CURRENT_UID}
    volumes:
      - .:/application
    networks:
      - quiz
    restart: unless-stopped

  database:
    image: mysql:8.0.21
    container_name: quiz-db
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:3306
    networks:
      - quiz
    restart: unless-stopped

networks:
  quiz:
    driver: bridge

volumes:
  data:
    name: mysql-data
